# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\0\Repos\SimplePlot\Grafico.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 509)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("plotTool.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(50, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonRect = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRect.sizePolicy().hasHeightForWidth())
        self.pushButtonRect.setSizePolicy(sizePolicy)
        self.pushButtonRect.setObjectName("pushButtonRect")
        self.gridLayout.addWidget(self.pushButtonRect, 1, 6, 2, 1)
        self.lineEditXinf = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditXinf.sizePolicy().hasHeightForWidth())
        self.lineEditXinf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEditXinf.setFont(font)
        self.lineEditXinf.setObjectName("lineEditXinf")
        self.gridLayout.addWidget(self.lineEditXinf, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.pushButtonVert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonVert.sizePolicy().hasHeightForWidth())
        self.pushButtonVert.setSizePolicy(sizePolicy)
        self.pushButtonVert.setObjectName("pushButtonVert")
        self.gridLayout.addWidget(self.pushButtonVert, 1, 7, 2, 1)
        self.pushButtonHome = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonHome.sizePolicy().hasHeightForWidth())
        self.pushButtonHome.setSizePolicy(sizePolicy)
        self.pushButtonHome.setObjectName("pushButtonHome")
        self.gridLayout.addWidget(self.pushButtonHome, 1, 9, 2, 1)
        self.pushButtonDelPlot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDelPlot.sizePolicy().hasHeightForWidth())
        self.pushButtonDelPlot.setSizePolicy(sizePolicy)
        self.pushButtonDelPlot.setObjectName("pushButtonDelPlot")
        self.gridLayout.addWidget(self.pushButtonDelPlot, 1, 5, 2, 1)
        self.lineEditYsup = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditYsup.sizePolicy().hasHeightForWidth())
        self.lineEditYsup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEditYsup.setFont(font)
        self.lineEditYsup.setObjectName("lineEditYsup")
        self.gridLayout.addWidget(self.lineEditYsup, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.lineEditYinf = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditYinf.sizePolicy().hasHeightForWidth())
        self.lineEditYinf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEditYinf.setFont(font)
        self.lineEditYinf.setObjectName("lineEditYinf")
        self.gridLayout.addWidget(self.lineEditYinf, 2, 0, 1, 1)
        self.pushButtonHor = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonHor.sizePolicy().hasHeightForWidth())
        self.pushButtonHor.setSizePolicy(sizePolicy)
        self.pushButtonHor.setObjectName("pushButtonHor")
        self.gridLayout.addWidget(self.pushButtonHor, 1, 8, 2, 1)
        self.pushButtonAddPlot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddPlot.sizePolicy().hasHeightForWidth())
        self.pushButtonAddPlot.setSizePolicy(sizePolicy)
        self.pushButtonAddPlot.setObjectName("pushButtonAddPlot")
        self.gridLayout.addWidget(self.pushButtonAddPlot, 1, 4, 2, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 8, 1, 1)
        self.lineEditNum = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNum.sizePolicy().hasHeightForWidth())
        self.lineEditNum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEditNum.setFont(font)
        self.lineEditNum.setObjectName("lineEditNum")
        self.gridLayout.addWidget(self.lineEditNum, 0, 9, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditEq = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEditEq.setFont(font)
        self.lineEditEq.setTabletTracking(False)
        self.lineEditEq.setObjectName("lineEditEq")
        self.gridLayout.addWidget(self.lineEditEq, 0, 2, 1, 2)
        self.lineEditStart = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditStart.sizePolicy().hasHeightForWidth())
        self.lineEditStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEditStart.setFont(font)
        self.lineEditStart.setObjectName("lineEditStart")
        self.gridLayout.addWidget(self.lineEditStart, 0, 5, 1, 1)
        self.lineEditStop = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditStop.sizePolicy().hasHeightForWidth())
        self.lineEditStop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEditStop.setFont(font)
        self.lineEditStop.setObjectName("lineEditStop")
        self.gridLayout.addWidget(self.lineEditStop, 0, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.lineEditXsup = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditXsup.sizePolicy().hasHeightForWidth())
        self.lineEditXsup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEditXsup.setFont(font)
        self.lineEditXsup.setObjectName("lineEditXsup")
        self.gridLayout.addWidget(self.lineEditXsup, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.pushButtonPlayMovie = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlayMovie.sizePolicy().hasHeightForWidth())
        self.pushButtonPlayMovie.setSizePolicy(sizePolicy)
        self.pushButtonPlayMovie.setMinimumSize(QtCore.QSize(75, 47))
        self.pushButtonPlayMovie.setObjectName("pushButtonPlayMovie")
        self.gridLayout.addWidget(self.pushButtonPlayMovie, 1, 10, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.lineEditDeltaT = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDeltaT.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditDeltaT.setObjectName("lineEditDeltaT")
        self.horizontalLayout.addWidget(self.lineEditDeltaT)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 10, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditEq, self.lineEditStart)
        MainWindow.setTabOrder(self.lineEditStart, self.lineEditStop)
        MainWindow.setTabOrder(self.lineEditStop, self.lineEditNum)
        MainWindow.setTabOrder(self.lineEditNum, self.lineEditDeltaT)
        MainWindow.setTabOrder(self.lineEditDeltaT, self.lineEditYinf)
        MainWindow.setTabOrder(self.lineEditYinf, self.lineEditYsup)
        MainWindow.setTabOrder(self.lineEditYsup, self.lineEditXinf)
        MainWindow.setTabOrder(self.lineEditXinf, self.lineEditXsup)
        MainWindow.setTabOrder(self.lineEditXsup, self.pushButtonAddPlot)
        MainWindow.setTabOrder(self.pushButtonAddPlot, self.pushButtonDelPlot)
        MainWindow.setTabOrder(self.pushButtonDelPlot, self.pushButtonRect)
        MainWindow.setTabOrder(self.pushButtonRect, self.pushButtonVert)
        MainWindow.setTabOrder(self.pushButtonVert, self.pushButtonHor)
        MainWindow.setTabOrder(self.pushButtonHor, self.pushButtonHome)
        MainWindow.setTabOrder(self.pushButtonHome, self.pushButtonPlayMovie)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Plot Tool with Python"))
        self.pushButtonRect.setText(_translate("MainWindow", "Zoom Rect\n"
"█"))
        self.lineEditXinf.setText(_translate("MainWindow", "0"))
        self.lineEditXinf.setPlaceholderText(_translate("MainWindow", "y inf"))
        self.label_4.setText(_translate("MainWindow", "x inf"))
        self.pushButtonVert.setText(_translate("MainWindow", "Zoom Vert\n"
"↕"))
        self.pushButtonHome.setText(_translate("MainWindow", "Zoom Home\n"
"⌂"))
        self.pushButtonDelPlot.setText(_translate("MainWindow", "Del Last Plot\n"
"(-)"))
        self.lineEditYsup.setText(_translate("MainWindow", "1"))
        self.lineEditYsup.setPlaceholderText(_translate("MainWindow", "x sup"))
        self.label_5.setText(_translate("MainWindow", "x sup"))
        self.lineEditYinf.setText(_translate("MainWindow", "-1"))
        self.lineEditYinf.setPlaceholderText(_translate("MainWindow", "x inf"))
        self.pushButtonHor.setText(_translate("MainWindow", "Zoom Hor\n"
"←→"))
        self.pushButtonAddPlot.setText(_translate("MainWindow", "Add New Plot\n"
"(+)"))
        self.label_7.setText(_translate("MainWindow", "Stop point"))
        self.label_8.setText(_translate("MainWindow", "Num of points"))
        self.lineEditNum.setText(_translate("MainWindow", "100"))
        self.lineEditNum.setPlaceholderText(_translate("MainWindow", "Num of pts"))
        self.label_2.setText(_translate("MainWindow", "y inf"))
        self.lineEditEq.setText(_translate("MainWindow", "sin(x)"))
        self.lineEditEq.setPlaceholderText(_translate("MainWindow", "Write Equation Here"))
        self.lineEditStart.setText(_translate("MainWindow", "0"))
        self.lineEditStart.setPlaceholderText(_translate("MainWindow", "Start point"))
        self.lineEditStop.setText(_translate("MainWindow", "7"))
        self.lineEditStop.setPlaceholderText(_translate("MainWindow", "Stop point"))
        self.label_3.setText(_translate("MainWindow", "y sup"))
        self.label_6.setText(_translate("MainWindow", "Start point"))
        self.lineEditXsup.setText(_translate("MainWindow", "7"))
        self.lineEditXsup.setPlaceholderText(_translate("MainWindow", "y sup"))
        self.label.setText(_translate("MainWindow", "Equation: f(x)"))
        self.pushButtonPlayMovie.setText(_translate("MainWindow", "Play Movie \n"
" in last plot\n"
"( ▍▍)"))
        self.label_9.setText(_translate("MainWindow", "Δt (s)"))
        self.lineEditDeltaT.setText(_translate("MainWindow", "1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

